name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@vitacore-company"
      - run: npm install
      - run: npm run compile
      - run: npm test
      - run: npm publish
